use_paper_preprocessing: True
data_file: "/rds/user/sakl2/hpc-work/development/frbayes2/frbayes/data/20191221A_original_data.h5"
original_freq_res: 24414.0625  # Hz
original_time_res: 0.98304e-3  # s
desired_freq_res: 3.125e6  # Hz
desired_time_res: 7.86432e-3  # s
freq_min: 400
freq_max: 800
max_peaks: 5
preprocessing:
  mode: "default"
file_root: "emg_test"
fit_pulses: True  # Set to True to fit the number of pulses
model: "exponential"
base_dir: "chains_emg"

# Prior ranges for model parameters
prior_ranges:
  # Common priors across all models
  amplitude:
    min: 0.0001
    max: 0.1
  tau:
    min: 0.1
    max: 1
  u:
    min: 0.01
    max: 4.0
  sigma:
    min: 0.00001
    max: 0.1
  
  # Model-specific priors
  emg:
    width:
      min: 0.001
      max: 0.3
  
  exponential:
    amplitude:  # Override common amplitude range for exponential model
      min: 0.001
      max: 0.1
  
  periodic_emg:
    width:
      min: 0.01
      max: 1.0
  
  periodic:
    u0:
      min: 0.001
      # max is calculated based on max_peaks
    period:
      min: 0.001
      # max is calculated based on max_peaks
