data_file: "/rds/user/sakl2/hpc-work/development/frbayes/data/20191221A_original_data.h5"
original_freq_res: 24414.0625  # Hz
original_time_res: 0.98304e-3  # s
desired_freq_res: 3.125e6  # Hz
desired_time_res: 7.86432e-3  # s
freq_min: 400
freq_max: 800
max_peaks: 12
file_root: "periodic_emg"
fit_pulses: False
model: "periodic_emg"
base_dir: "chains"
