data_file: "data/20191221A_original_data.h5"
original_freq_res: 24414.0625  # Hz
original_time_res: 0.98304e-3  # s
desired_freq_res: 3.125e6  # Hz
desired_time_res: 7.86432e-3  # s
max_peaks: 6
file_root: "simple_gaussian"
fit_pulses: False
